networks:
  traefik_default:
    external: true

services:
  whoami:
    container_name: whoami
    image: traefik/whoami
    restart: always
# port to test if the server ip is properly reachable by doing http://IP:9452
#    ports:
#      - 9452:80
# network to ensure that the reverse-proxy works properly
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`test.hugowillaume.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
