services:
  hangyoutube:
    container_name: hang_youtube
    restart: always
    image: ghcr.io/alexta69/metube:2025.12.14
    mem_limit: 1400m
    cpus: 0.8
    networks:
      - traefik_default
    volumes:
      - /home/hurlu/music:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hangyoutube.rule=Host(`youtube.hang.hugowillaume.com`)"
      - "traefik.http.routers.hangyoutube.entrypoints=websecure"
      - "traefik.http.routers.hangyoutube.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.hangyoutube.loadbalancer.server.port=8081"
      - "traefik.http.routers.hangyoutube.middlewares=traefik-forward-auth"


  hangspotify:
    container_name: hang_spotify
    image: ghcr.io/henriquesebastiao/downtify:1.1.1
    restart: always
    networks:
      - traefik_default
    volumes:
      - /home/hurlu/music:/downloads
    mem_limit: 1400m
    cpus: 0.8
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hangspotify.rule=Host(`spotify.hang.hugowillaume.com`)"
      - "traefik.http.routers.hangspotify.entrypoints=websecure"
      - "traefik.http.routers.hangspotify.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.hangspotify.loadbalancer.server.port=8000"
      - "traefik.http.routers.hangspotify.middlewares=traefik-forward-auth"

networks:
  traefik_default:
    external: true
